import type { DbcRecipe, ScenarioComparison } from '../domain/types';
import { simulateCurveSlippageProgression } from './curveMath';

/**
 * Builds an analytical side-by-side comparison across candidate DBC recipes.
 * Strictly categorizes metrics into:
 * 1. Selected protocol constants/input arithmetic
 * 2. Derived Calculations
 * 3. Assumption-Dependent Simulations
 * 4. Post-Graduation DAMM v2 Metrics
 */
export function buildScenarioComparison(recipes: DbcRecipe[]): ScenarioComparison {
  const metricsComparison: ScenarioComparison['metricsComparison'] = [];

  // Metric 1: Base Fee Numerator (Exact Protocol)
  const baseFeeNumerators: Record<string, string> = {};
  recipes.forEach((r) => {
    const bps = r.requirements.feePreferences.baseFeeBps;
    baseFeeNumerators[r.id] = `${bps} bps (${((bps / 10000) * 1_000_000_000).toLocaleString()} num)`;
  });
  metricsComparison.push({
    label: 'Initial Base Fee & On-Chain Numerator',
    category: 'Exact Protocol Calculation',
    unit: 'bps (numerator / 1B)',
    values: baseFeeNumerators,
    formulaOrExplanation: 'fee_numerator = round((bps / 10,000) * 1,000,000,000)',
  });

  // Metric 2: Curve mode is input data; segment count is from our visualization model.
  const curveModes: Record<string, string> = {};
  recipes.forEach((r) => {
    curveModes[r.id] = `Mode ${r.requirements.buildCurveMode} (${r.segments.length} segment${r.segments.length > 1 ? 's' : ''})`;
  });
  metricsComparison.push({
    label: 'Curve Construction Mode & Segments',
    category: 'Derived Calculation',
    unit: 'mode / analytical segments',
    values: curveModes,
    formulaOrExplanation: 'Mode is the selected input. Segment count is generated by CurveScope analytical geometry, not an SDK-decoded protocol curve.',
  });

  // Metric 3: Estimated from the analytical segment model.
  const quoteRaises: Record<string, string> = {};
  recipes.forEach((r) => {
    quoteRaises[r.id] = `${r.derivedMetrics.quoteNeededToGraduate.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${r.requirements.quoteSymbol}`;
  });
  metricsComparison.push({
    label: 'Quote Reserve at Graduation Threshold',
    category: 'Assumption-Dependent Simulation',
    unit: 'quote tokens',
    values: quoteRaises,
    formulaOrExplanation: 'CurveScope estimate from its selected segment geometry; does not verify the exported/on-chain migration threshold.',
  });

  // Metric 4: Starting Price (Derived Calculation)
  const initPrices: Record<string, string> = {};
  recipes.forEach((r) => {
    initPrices[r.id] = `${r.derivedMetrics.initialPriceQuote.toExponential(4)} ${r.requirements.quoteSymbol}`;
  });
  metricsComparison.push({
    label: 'Starting Price (Quote / Base)',
    category: 'Derived Calculation',
    unit: 'quote/base',
    values: initPrices,
    formulaOrExplanation: 'P_initial = InitialMarketCap / TotalSupply',
  });

  // Metric 5: Migration Price (Derived Calculation)
  const migPrices: Record<string, string> = {};
  recipes.forEach((r) => {
    migPrices[r.id] = `${r.derivedMetrics.migrationPriceQuote.toExponential(4)} ${r.requirements.quoteSymbol}`;
  });
  metricsComparison.push({
    label: 'Migration Price (Quote / Base)',
    category: 'Derived Calculation',
    unit: 'quote/base',
    values: migPrices,
    formulaOrExplanation: 'P_migration = (sqrt(P_migration))^2 from top curve segment',
  });

  // Metric 6: Price Discovery Multiple (Derived Calculation)
  const multipliers: Record<string, string> = {};
  recipes.forEach((r) => {
    multipliers[r.id] = `${r.derivedMetrics.priceMultiplier.toFixed(2)}x`;
  });
  metricsComparison.push({
    label: 'Price Appreciation Multiple',
    category: 'Derived Calculation',
    unit: 'multiplier',
    values: multipliers,
    formulaOrExplanation: 'Multiple = P_migration / P_initial',
  });

  // Metric 7: Post-Graduation DAMM v2 Base Liquidity (Post-Graduation DAMM v2)
  const dammBaseTokens: Record<string, string> = {};
  recipes.forEach((r) => {
    dammBaseTokens[r.id] = `${r.derivedMetrics.baseTokensMigrated.toLocaleString()} (${r.requirements.percentageSupplyOnMigration}%)`;
  });
  metricsComparison.push({
    label: 'Base Tokens Migrated to DAMM v2',
    category: 'Post-Graduation DAMM v2',
    unit: 'base tokens (% supply)',
    values: dammBaseTokens,
    formulaOrExplanation: 'base_migrated = TotalSupply * (percentageSupplyOnMigration / 100)',
  });

  // Metric 8: DAMM v2 Quote Liquidity Seeding (Post-Graduation DAMM v2)
  const dammQuotes: Record<string, string> = {};
  recipes.forEach((r) => {
    dammQuotes[r.id] = `${r.derivedMetrics.quoteReserveToDammV2.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${r.requirements.quoteSymbol}`;
  });
  metricsComparison.push({
    label: 'Net Quote Liquidity Seeded into DAMM v2',
    category: 'Post-Graduation DAMM v2',
    unit: 'quote tokens',
    values: dammQuotes,
    formulaOrExplanation: 'CurveScope estimate after modeled deductions; migration fee configuration is not fully represented in the current recipe schema.',
  });

  // Metric 9: Fixed Protocol Migration Fee (Exact Protocol)
  const protocolMigFees: Record<string, string> = {};
  recipes.forEach((r) => {
    protocolMigFees[r.id] = `${r.derivedMetrics.protocolMigrationFeeQuote.toLocaleString(undefined, { maximumFractionDigits: 4 })} ${r.requirements.quoteSymbol} (0.2%)`;
  });
  metricsComparison.push({
    label: 'Estimated Protocol Migration Deduction (0.2%)',
    category: 'Assumption-Dependent Simulation',
    unit: 'quote tokens',
    values: protocolMigFees,
    formulaOrExplanation: 'Illustrative application of the documented 0.2% fee to CurveScope’s estimated threshold; exact SDK/on-chain amount is not queried.',
  });

  // Slippage progression simulation at 25%, 50%, 75%, 100%
  const slippageSimulation: ScenarioComparison['slippageSimulation'] = [25, 50, 75, 100].map((fillPct) => {
    const priceQuote: Record<string, number> = {};
    const cumulativeQuoteSpent: Record<string, number> = {};
    const effectivePricePaid: Record<string, number> = {};

    recipes.forEach((r) => {
      const sim = simulateCurveSlippageProgression(r.segments, [fillPct / 100])[0];
      priceQuote[r.id] = sim ? sim.currentPriceQuote : 0;
      cumulativeQuoteSpent[r.id] = sim ? sim.quoteSpent : 0;
      effectivePricePaid[r.id] = sim ? sim.effectiveAveragePrice : 0;
    });

    return {
      fillPercentage: fillPct,
      priceQuote,
      cumulativeQuoteSpent,
      effectivePricePaid,
    };
  });

  return {
    recipes,
    metricsComparison,
    slippageSimulation,
  };
}
